### ISSUE TITLE
Factorio calculator

### ISSUE THREAD

**Issue by math625f** [dbeckwith/factorio-resource-map-markers#1]
Hey man! 

I know this isn't an optimal means of contacting you, but I've read your [blog post](http://dbeckwith.com/2017/04/24/factorio-calculator/) regarding Factorio recipe trees, in which you mentioned you might release your source code at some point. I looked through you repositories, and I was unable to locate it in there. Do you still have it - and would you be willing to share it?

Best regards.

**Comment by dbeckwith** [comment]
That post was from a while ago... I've gone through various iterations of trying to implement that same idea with different approaches and always ran into a brick wall. It's tricky because I eventually realized technically Factorio recipes don't form a tree, they form a graph because there can be multiple ways to create an item, especially once you start adding in mods.

I don't know if I even have the original code for the example in the post anymore. Even if I did I doubt it would still work, the way I was loading the data from the game was very fragile and buggy. I've learned a lot from later attempts though, if you have questions about how to do specific things I'm happy to help.

**Comment by math625f** [comment]
My original idea was parsing the files directly using Python, but that quickly turned out to be more difficult than I had anticipated, due to Lua’s seemingly weird structure (although I think it’s starting to make more sense now). I then thought that someone had to have been doing something similar to me, and that was when I stumbled on your post. 

I don’t necessarily want to create a graph representing the recipes, I’m just looking for a simpler way to quickly get an overview of some of the more complex recipes in Bobs/Angels.

**Comment by dbeckwith** [comment]
Okay yeah, one thing I quickly realized is that parsing the files directly isn't going to work, because it's actual *code*. So you need to *run it* as code. The way I've been doing it recently is pretty involved but it works very reliably. Essentially the strategy is:
* Run the actual Factorio game to get it to load all the data files the way it wants (which is very complicated and hard to reproduce manually).
* Use a mod to dump all the prototype data.
* Load the data from that dump.

Here are the detailed steps:
* First, find the Factorio game directory and look at all the installed mods (using `mods/mod-list.json`).
* Create a temporary mod in the `mods/` directory named `data-dumper` or something. As of 0.18.31 mods can be just a directory (don't have to bother making a zip file).
  * In the mod's `info.json`, set its `dependencies` list to the full list of all installed mods (including `base`). This will ensure that the mod loads absolutely last in the startup process.
  * Create a file named `data-final-fixes.lua` with the content `print(serpent.dump(data.raw))`.
* Add the mod to `mod-list.json` with `enabled: true`.
* Now that the mod is set up, you can run the game (using for example the `subprocess` Python module). This may differ a bit depending on if you're using the Steam version or not. I'm not using the Steam version, and I'm on Linux. These are the command line arguments I pass to the game: `--low-vram --disable-audio --disable-prototype-history`, which make it load much faster than normal. You can see the list of arguments [here](https://wiki.factorio.com/Command_line_parameters), or run the game with `--help`. I think there's more you can do to launch it in headless mode so it doesn't even render a window, but I haven't tested that out too much. When you launch it, make sure you pipe stdout so you can follow it as the game runs. When you see the line `Loading mod data-dumper 0.1.0 (data-final-fixes.lua)`, the next line will contain all of the prototype data from `data.raw`. Then you let the game finish starting up and when you see the line `Factorio initialised`, you can just kill the process. There might be some way to tell the game to exit as soon as it finishes starting up, but this works fine.
* As a cleanup step, remove the temporary mod so it doesn't load the next time you play the game for real.
* At this point, you have the output from `serpent.dump(data.raw)`, which it took me a while to realize is *still* not something you can just parse. Because the Lua tables can contain self-references, what `serpent` outputs is actually still Lua code (a Lua module actually). So at this point you need to run a Lua interpreter like [lupa](https://pypi.org/project/lupa/). Evaluate the serpent output in the Lua runtime and it will convert it to a Python object which you can then dump as JSON to save it somewhere or do whatever you want with it. I would recommend caching it in a file as JSON so you don't have to run the game every time your program starts.

Let me know if any of that is confusing.

**Comment by math625f** [comment]
Hey man! 
With your help - after some tinkering - I've finally managed to produce a json file, containing the data from Factorio. 
Thanks a lot!
I'll probably continue this thread if I have any more inquiries, although I'll close this issue for now, since it's not relevant to this repository ^^.
